### ISSUE TITLE
Fractal as serializer for FosRestBundle

### ISSUE THREAD

**Issue by matiux** [samjarrett/FractalBundle#1]
hi,
I used Fractal in Laravel, and now I'm trying the symfony bundle. It works, but I would like embed Fractal as serializer in FosRestBundle in order to replace jsmserializer with Fractal. 

Can anyone give me suggestions?

**Comment by samjarrett** [comment]
Hey @matiux, you might want to check with the actual fractal maintainers? https://github.com/thephpleague/fractal
