### ISSUE TITLE
Packagist.org is not auto-updating

### ISSUE THREAD

**Issue by dave-redfern** [samjarrett/FractalBundle#14]
I reported this issue on the SF5 PR, but it may have got lost.

The link between your repo and packagist is broken; likely running on the old integration. Could you update your packagist connection to pull in the new version / reconnect to get updates. It's holding up some of my work (I need SF5 support).

Thanks!

**Comment by samjarrett** [comment]
Fixed, sorry about that.

**Comment by dave-redfern** [comment]
@samjarrett Awesome thanks!
