### ISSUE TITLE
Warning: Cannot bind closure to scope of internal class ReflectionProperty

### ISSUE THREAD

**Issue by arisultima** [samjarrett/FractalBundle#9]
hi, im trying to use this package in symfony 2.8 and im using eloquent for entities

i have setup everything like the documentation but im getting this error

Warning: Cannot bind closure to scope of internal class ReflectionProperty

**Comment by samjarrett** [comment]
Hey @narutimateum, I'm not able to replicate this with my installation on Symfony 2.8/3.2, so I'd recommend posting example code when reporting an issue and including the entire error, however this bundle doesn't make use of any of the `Reflection` classes (e.g. `ReflectionProperty`), so your issue might be upstream in [thephpleague/fractal](https://github.com/thephpleague/fractal) or elsewhere.

If you can provide example code to replicate the issue, happy to look into it further?

Thanks,
Sam
